version: 2
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: spikerlabs/scala-sbt:scala-2.12.1-sbt-0.13.15
    steps:
      - deploy:
          name: Maybe deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
              sbt docker:publish
            fi